#!/usr/bin/env python
# -*- coding: utf-8 -*-

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('conanbuildinfo_waf', tooldir=".");

def build(bld):
    bld.program(source='timer.cpp', target='timer', use='Poco')
