#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

    conf.load('conanbuildinfo_waf', tooldir=[".", conf.bldnode.abspath()]);

def build(bld):
    bld.program(source='example.cpp', target='example', use='Hello')
